import { Geist, Geist_Mono, Public_Sans } from 'next/font/google';
import localFont from 'next/font/local';
import type { Metadata } from 'next';
import { ConfigProvider } from 'antd';
import './globals.css';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import Jumbotron from '@/components/Jumbotron';
import Header from '@/components/Header';
import Fotter from '@/components/Fotter';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const epilogue = localFont({
  src: [{ path: '/fonts/Epilogue-VariableFont_wght.ttf', style: 'normal' }],
});

export const publicSans = Public_Sans();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${epilogue.className} antialiased`}>
        <AntdRegistry>
          <ConfigProvider
            theme={{
              components: {
                Collapse: {
                  headerBg: '#fff',
                },
              },
            }}
          >
            <Header />
            {children}
            <Jumbotron />
            <Fotter />
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
